import Head from "next/head";
import { Inter } from "next/font/google";
import Hero from "@/components/home/Hero";
import Nails_Cntr from "@/components/home/Nails_Cntr";
import ProductCards from "@/components/home/ProductCards";
import Section5 from "@/components/about/Section5";
import Section6 from "@/components/about/Section6";
import Section7 from "@/components/about/Section7";
import Section8 from "@/components/about/Section8";

const inter = Inter({ subsets: ["latin"] });

export default function About() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Section5/>
        <Section6/>
        <Section7/>
        <Section8/>
        {/* <Hero /> */}
        <Nails_Cntr />
        {/* <ProductCards /> */}
      </main>
    </>
  );
}
