import Head from "next/head";
import { Inter } from "next/font/google";
import Hero from "@/components/home/Hero";
import Nails_Cntr from "@/components/home/Nails_Cntr";
import ProductCards from "@/components/home/ProductCards";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <Hero /> */}
        {/* <Nails_Cntr /> */}
        {/* <ProductCards /> */}
      </main>
    </>
  );
}
